version: '3.8'
services:
  # Searxng Service
  searxng:
    build:
      context: ./backend
      dockerfile: ./searxng.dockerfile
    expose:
      - 4000
    ports:
      - 4000:8080
    networks:
      - zealer-search

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
    expose:
      - 3001
    ports:
      - 3001:3001
    networks:
      - zealer-search
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:3001
        - NEXT_PUBLIC_API_URL=http://127.0.0.1:3001/api
    depends_on:
      - backend
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - zealer-search
    environment:
      - NODE_ENV=production
    restart: unless-stopped

networks:
  zealer-search:
